name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-latest]
        include:
          - os: windows-2022
          - os: ubuntu-latest
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: LuaUnlocker

      - name: Checkout Metamod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: mmsource-2.0
          submodules: recursive

      - name: Checkout HL2SDK
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/hl2sdk
          ref: cs2
          path: hl2sdk-cs2

      - name: Patch HL2SDK (va_list fix)
        run: |
          sed -i 's/m_ReuseList = List;/va_copy(m_ReuseList, List);/g' hl2sdk-cs2/public/tier0/platform.h

      - name: Install Protobuf (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libprotobuf-dev

      - name: Install Protobuf (Windows)
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          # Install vcpkg and protobuf
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
          
          # Set protobuf version
          $version = "3.21.12"
          $portfile = "vcpkg/ports/protobuf/portfile.cmake"

          # Checkout specific protobuf version
          git -C vcpkg fetch origin
          git -C vcpkg checkout "2025.07.21" -- ports/protobuf
    
          # Edit portfile to pin version
          (Get-Content $portfile) -replace '^set\(VERSION .*$', "set(VERSION $version)" | Set-Content $portfile
    
          # Install protobuf
          ./vcpkg/vcpkg install protobuf --triplet x64-windows-static
    
          # Set environment variables
          $protobufPath = "$pwd/vcpkg/installed/x64-windows-static"
          $protocPath = "$protobufPath/tools/protobuf/protoc.exe"
          $includePath = "$protobufPath/include"
    
          # Verify installation
          if (-not (Test-Path $protocPath)) { throw "protoc.exe not found at $protocPath" }
          if (-not (Test-Path "$includePath/google/protobuf")) { throw "protobuf headers missing" }
    
          # Set environment variables
          echo "PROTOBUF_INCLUDE=$includePath" >> $env:GITHUB_ENV
          echo "PROTOC_PATH=$protocPath" >> $env:GITHUB_ENV
    
          # Debug output
          Write-Output "Installed protobuf version: $version"
          Get-ChildItem "$includePath/google/protobuf/descriptor.pb.h"

      - name: Verify Protobuf Installation1
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          Write-Output "Verifying protobuf installation..."
          if (-not (Test-Path $env:PROTOBUF_INCLUDE)) {
            throw "PROTOBUF_INCLUDE path not found: $env:PROTOBUF_INCLUDE"
          }
          if (-not (Test-Path $env:PROTOC_PATH)) {
            throw "PROTOC_PATH not found: $env:PROTOC_PATH"
          }
          Write-Output "Protobuf headers found at: $env:PROTOBUF_INCLUDE"
          Write-Output "Protoc found at: $env:PROTOC_PATH"
          Get-ChildItem "$env:PROTOBUF_INCLUDE/google/protobuf/runtime_version.h"
      
      - name: Regenerate Protobuf Files (Windows)
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          $protoc = "$env:PROTOC_PATH"
          cd LuaUnlocker/protobuf
          & $protoc --cpp_out=generated -I . -I include *.proto
          Copy-Item generated/*.pb.h -Destination ../../hl2sdk-cs2/public/ -Force

      - name: Regenerate Protobuf Files (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd LuaUnlocker/protobuf
          protoc --cpp_out=generated *.proto

      - name: Copy Protobuf Headers to SDK (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p hl2sdk-cs2/public
          cp LuaUnlocker/protobuf/generated/*.pb.h hl2sdk-cs2/public/

      - name: Copy Protobuf Headers to SDK (Windows)
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path hl2sdk-cs2/public
          Copy-Item -Path LuaUnlocker/protobuf/generated/*.pb.h -Destination hl2sdk-cs2/public/


      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        run: |
          cd ambuild && python setup.py install && cd ..

      - name: Install Clang 16
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt update && apt install -y clang-16
          ln -sf /usr/bin/clang-16 /usr/bin/clang && ln -sf /usr/bin/clang++-16 /usr/bin/clang++

      - name: Verify libtier0.so (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          if [ ! -f "hl2sdk-cs2/lib/linux64/libtier0.so" ]; then
            echo "libtier0.so missing - creating dummy file"
            mkdir -p hl2sdk-cs2/lib/linux64
            touch hl2sdk-cs2/lib/linux64/libtier0.so
          fi

      - name: Verify Protobuf Headers (Windows)
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          dir /s /b "%PROTOBUF_INCLUDE%\google\protobuf\runtime_version.h"
          echo INCLUDE=%INCLUDE%
          echo PROTOBUF_INCLUDE=%PROTOBUF_INCLUDE%

      - name: Validate MSVC Setup (Windows)
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl.exe /?
          where cl.exe
          echo INCLUDE=%INCLUDE%

      - name: Build (Windows)
        if: matrix.os == 'windows-2022'
        working-directory: LuaUnlocker
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%PROTOBUF_INCLUDE%;%INCLUDE%
          set AMBUILD_CXX_STANDARD=17
          mkdir build
          cd build
          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --include-dir /usr/include
          ambuild

      - name: Build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: LuaUnlocker
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --include-dir /usr/include
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: LuaUnlocker/build/package

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Package
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          if [ -d "./Linux/" ]; then
            cd ./Linux/
            tar -czf ../${{ github.event.repository.name }}-${version}-linux.tar.gz addons
            cd -
          fi
          if [ -d "./Windows/" ]; then
            cd ./Windows/
            zip -r ../${{ github.event.repository.name }}-${version}-windows.zip addons
            cd -
          fi

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.event.repository.name }}-*
          tag: ${{ github.ref }}
          file_glob: true
